### ISSUE TITLE
Versioning question

### ISSUE THREAD

**Issue by AkhilNairAmey** [rocker-org/hadleyverse#11]
When running the images I see

```
docker run -it --rm rocker/hadleyverse:3.3.2 R

R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```
which makes sense to me.  I also see, however,

```
docker run -it --rm rocker/hadleyverse:3.3.1 R

R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```
where I was looking to update my docker images R version to `3.4.0`.

Is this the correct tagging - or have I misunderstood the system? 

Thanks,
Akhil

**Comment by cboettig** [comment]
Looks like that tag got dropped on 3.3.1. should be fixed soon, sorry. 

Please note this image has been deprecated in favor of `tidyverse` or `verse`, see https://github.com/rocker-org/rocker-versioned, and is no longer actively maintained.  I'd strongly encourage any user to migrate to `verse` and open an issue in the `rocker-versioned` repo if there's anything in `hadleyverse` you are missing in `verse`.

**Comment by AkhilNairAmey** [comment]
Okay thanks - will open an issue re; `rJava`.

**Comment by cboettig** [comment]
The java dependencies are already in place in `rocker/verse` so you should merely need to do `install.packages("rJava")` and it'll work.  Still, we could build it in ahead of time I suppose.  
Cheers,
